---@alias DamageType
--- | "slashing"   # Damage dealt by swords, axes, etc.
--- | "piercing"   # Damage dealt by arrows, spears, etc.
--- | "bludgeoning" # Damage dealt by hammers, maces, etc.
--- | "fire"       # Magical or environmental fire damage
--- | "cold"       # Magical or environmental cold damage
--- | "lightning"  # Magical lightning damage
--- | "thunder"    # Sound-based magical damage
--- | "acid"       # Corrosive damage
--- | "poison"     # Toxic or venomous damage
--- | "necrotic"   # Death-related magical damage
--- | "radiant"    # Holy or light-based magical damage
--- | "psychic"    # Mind-based damage
--- | "force"      # Pure magical energy damage