---@meta example
--- @type FloorCell
prism.cells.Floor = nil
--- @type WallCell
prism.cells.Wall = nil
--- @type AttackAction
prism.actions.Attack = nil
--- @type EndTurnAction
prism.actions.EndTurn = nil
--- @type MoveAction
prism.actions.Move = nil
--- @type SRDAction
prism.actions.SRDAction = nil
--- @type SightComponent
prism.components.Sight = nil
--- @type SRDStatsComponent
prism.components.SRDStats = nil
--- @type PlayerActor
prism.actors.Player = nil
--- @type SightSystem
prism.systems.Sight = nil